config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'shoppers#home'

  get  '/signup',  to: 'shoppers#home'
  post '/signup',  to: 'users#create'

  get '/shoppers/welcome/' => 'users#welcome', :as => :welcome_user

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :funnels, only: [:index]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  WORKFLOW_STATES = ['applied', 'quiz_started', 'quiz_completed', 'onboarding_requested', 'onboarding_completed', 'hired', 'rejected']

  before_save { self.email = email.downcase }
  before_validation :initial_workflow_state, on: :create
  before_validation :initial_background_check, on: :create

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :first_name, presence: true,
                    length: { minimum: 3, maximum: 50 }

  validates :last_name, presence: true,
                    length: { minimum: 3, maximum: 50 }

  validates :phone_number, presence: true, uniqueness: true

  validates :zip_code, presence: true

  validates :workflow_state, presence: true

  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  private
    def initial_workflow_state
      self.workflow_state = WORKFLOW_STATES.first unless workflow_state
    end

    def initial_background_check
      self.permission = false
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
    render html: "hello, world!"
  end

end

app/controllers/funnels_controller.rb
class FunnelsController < ApplicationController
  def index
    @funnel = serialized_response

    respond_to do |format|
      format.html { @chart_funnel = formatted_funnel }
      format.json { render json: @funnel }
    end
  end

  private

  # generates a formatted version of the funnel for display in d3
  def formatted_funnel
    formatted = Hash.new { |h, k| h[k] = [] }

    @funnel.each do |date, state_counts|
      state_counts.each do |state, count|
        formatted[state] << {label: date, value: count}
      end
    end

    formatted.map do |k, v|
      {
        key: k.humanize,
        values: v
      }
    end
  end

  def serialized_response
    hash = {}
    start_date = params[:start_date].try(:to_date) || Date.today
    end_date = params[:end_date].try(:to_date) || Date.today
    query = FunnelsQuery.new(start_date, end_date)
    result = query.results
    result.each do |res|
      monday = res["monday"]
      sunday = res["sunday"]
      key = [monday, sunday].join("-")
      hash[key] = {} if hash[key].nil?
      hash[key][res["workflow_state"]] = res["count"]
    end
    return hash
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/shoppers_controller.rb
class ShoppersController < ApplicationController
  def home
    @user = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      permission(@user)
    else
      render 'new'
    end
  end

  def permission(user)
    @curr_user = user
    render 'permission'
  end

  def welcome
    @applicant = User.find(params[:id])
    if params[:status]
      flash[:success] = "Welcome to the instacart!"
      log_in @applicant
      @applicant.update_attribute(:permission, true)
      @applicant.save
    else
      @applicant.delete
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end


  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :zip_code, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funnels_helper.rb
module FunnelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


end

app/helpers/shoppers_helper.rb
module ShoppersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/funnels/index.html.erb
<h1>Funnels API</h1>
<!-- <a href="http://localhost:3000/funnels.json?start_date=2014-12-01&end_date=2014-12-31">Funnels 12/1/14 - 12/31/14</a> -->

<h2>
  <a href="https://ehsan-instacart.herokuapp.com/funnels.json?start_date=2014-12-01&end_date=2014-12-31">Funnels => 12/1/14 - 12/31/14</a>
</h2>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <ul>
      <div class="text-center center-block">
            <a href="https://www.facebook.com/Instacart/"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
            <a href="https://www.instagram.com/instacart/"><i id="social-fb" class="fa fa-instagram fa-3x social"></i></a>
            <a href="https://twitter.com/instashoppers?lang=en"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
            <a href="https://plus.google.com/+Instacart"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
            <a href="mailto:shoppers@instacart.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
      </div>
    </ul>
  </nav>

  <small>
      <%= link_to image_tag("instaCa.jpg", alt: "instacart logo", class:"fa-facebook-square social footer-image-container"), 'http://www.instacart.com/' %>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>

    <header class="header">
      <small>
        <%= link_to image_tag("Instacart_logo_header.png", alt: "instacart logo", class:"header-image-container"), 'http://www.instacart.com/' %>
      </small>
    </header>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaCart</title>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_signup_form.html.erb
<div class="signup">
  <div class="row">
      <h1 class="display-2" >Sign up</h1>
        <%= render 'shared/error_messages' %>
        <%= form_for(@user, url: signup_path) do |f| %>
  			<hr class="colorgraph">
  			<div class="row">
  				<div class="col-xs-12 col-sm-6 col-md-6">
  					<div class="form-group">
              <%= f.text_field :first_name, :class => "form-control input-lg", :placeholder => "First Name", :tabindex => 1 %>
  					</div>
  				</div>
  				<div class="col-xs-12 col-sm-6 col-md-6">
  					<div class="form-group">
               <%= f.text_field :last_name, :class => "form-control input-lg", :placeholder => "Last Name", :tabindex => 2 %>
  					</div>
  				</div>
  			</div>
        <div class="form-group">
          <%= f.email_field :email, :class => "form-control input-lg", :placeholder => "Email Address (john@example.com)", :tabindex => 3 %>
  			</div>
  			<div class="form-group">
          <%= f.text_field :phone_number, :class => "form-control input-lg", :placeholder => "Phone Number", :tabindex => 4 %>
  			</div>
        <div class="form-group">
          <%= f.text_field :zip_code, :class => "form-control input-lg", :placeholder => "Zip code", :tabindex => 5 %>
  			</div>
        <div class="form-group">
          <%= f.text_field :ref_code, :class => "form-control input-lg", :placeholder => "Referral Code (optional)", :tabindex => 6 %>
  			</div>

  			<div class="form-group">
          <%= f.password_field :password, :class => "form-control input-lg", :placeholder => "Password", :tabindex => 7 %>
  			</div>

  			<div class="form-group">
          <%= f.password_field :password_confirmation, :class => "form-control input-lg", :placeholder => "Confirm Password", :tabindex => 8 %>
  			</div>

        <hr class="colorgraph">
  			<div class="form-group">
          <%= f.submit "Apply Now", :class => "btn btn-primary btn-block btn-lg", :tabindex => 9 %>
        </div>
        <% end %>
  	</div>
  </div>
</div>

app/views/shared/_youtube_video.html.erb
<div>
  <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="//www.youtube.com/embed/B9VZ5CbZj2I"></iframe>
  </div>
</div>

app/views/shoppers/home.html.erb
<h1 class="display-1">Welcome</h1>
<div class="maincontainer">
  <div class="col-md-8">
    <div class="col-md-12">
      <%= render 'shared/youtube_video'%>
    </div>
      <div class="col-md-12 benefits">
        <h1>Positions at Instacart</h1>
        <div class="col-md-6">
            <h2>No Car</h2>
            <h3>Shopper</h3>
            <h3>Cashier</h3>
        </div>
        <div class="col-md-6">
            <h2>Car Required</h2>
            <h3>Driver</h3>
            <h3>Driver+Shopper</h3>
        </div>
      </div>
  </div>
  <div class="col-md-4">
    <%= render 'shared/signup_form' %>
  </div>

</div>

app/views/users/edit.html.erb
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages', object: @user %>
      <%= form_for(@user) do |f| %>
			  <hr class="colorgraph">
  			<div class="row">
  				<div class="col-xs-12 col-sm-6 col-md-6">
  					<div class="form-group">
              <%= f.text_field :first_name, :class => "form-control input-lg", :placeholder => "First Name", :tabindex => 1 %>
  					</div>
  				</div>
  				<div class="col-xs-12 col-sm-6 col-md-6">
  					<div class="form-group">
               <%= f.text_field :last_name, :class => "form-control input-lg", :placeholder => "Last Name", :tabindex => 2 %>
  					</div>
  				</div>
  			</div>
        <div class="form-group">
          <%= f.email_field :email, :class => "form-control input-lg", :placeholder => "Email Address (john@example.com)", :tabindex => 3 %>
  			</div>
  			<div class="form-group">
          <%= f.text_field :phone_number, :class => "form-control input-lg", :placeholder => "Phone Number", :tabindex => 4 %>
  			</div>
        <div class="form-group">
          <%= f.text_field :zip_code, :class => "form-control input-lg", :placeholder => "Zip code", :tabindex => 5 %>
  			</div>

  			<div class="form-group">
          <%= f.password_field :password, :class => "form-control input-lg", :placeholder => "Password", :tabindex => 7 %>
  			</div>

  			<div class="form-group">
          <%= f.password_field :password_confirmation, :class => "form-control input-lg", :placeholder => "Confirm Password", :tabindex => 8 %>
  			</div>

        <hr class="colorgraph">
  			<div class="form-group">
          <%= f.submit "Save changes", :class => "btn btn-primary btn-block btn-lg", :tabindex => 9 %>
        </div>
      <% end %>
   </div>
</div>

app/views/users/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= render 'shared/signup_form' %>
</div>

app/views/users/permission.html.erb
<div class="row">
  <div class="col-md-12 display-3">
    <h1>Apply to be a Shopper - Background Check Acceptance</h1>
    <p>
      I hereby authorize and Instacart designated agents and representatives to conduct a comprehensive review of my background to evaluate if
      I am qualified for the position for which I am applying. I understand that Instacart will utilize an outside firm or firms to
      assist it in checking such information, and I specifically authorize such an investigation by information
      services and outside entities of the company's choice.

      I understand that information contained in my employment or contractor application, or otherwise disclosed by
      me before or during my employment or contract assignment, if any, may be used for the purpose of
      obtaining and evaluating background check reports on me. I also understand that nothing
      herein shall be construed as an offer of employment or contract for services.

      I agree with all the above terms
    </p>
    <%= link_to( "I Agree", welcome_user_path(status: true, id:@curr_user.id), class: "btn btn-lg btn-primary") %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.first_name %> || <%= @user.email %>

app/views/users/welcome.html.erb
<h1><%= @applicant.first_name %></h1>
<h3>Your application was successfully submitted!</h3>
<p>We will now review it, and get back to you within 3-5 business days.</p>